-- Core Snowflake objects for the DeepSequence feedback lake-to-warehouse path.
-- Run with a role that is allowed to create the database/schema objects below.

CREATE DATABASE IF NOT EXISTS DEEPSEQUENCE_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS DEEPSEQUENCE_ANALYTICS.RECOMMENDER;

CREATE FILE FORMAT IF NOT EXISTS DEEPSEQUENCE_ANALYTICS.RECOMMENDER.FEEDBACK_JSON
    TYPE = JSON
    COMPRESSION = AUTO;

CREATE TABLE IF NOT EXISTS DEEPSEQUENCE_ANALYTICS.RECOMMENDER.RAW_FEEDBACK (
    PAYLOAD VARIANT NOT NULL,
    SOURCE_FILENAME STRING,
    SOURCE_ROW_NUMBER NUMBER,
    LOADED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE VIEW DEEPSEQUENCE_ANALYTICS.RECOMMENDER.RECOMMENDATION_FEEDBACK AS
SELECT
    PAYLOAD:schema_version::NUMBER AS SCHEMA_VERSION,
    PAYLOAD:event_id::STRING AS EVENT_ID,
    PAYLOAD:impression_id::STRING AS IMPRESSION_ID,
    PAYLOAD:anonymous_user_id::STRING AS ANONYMOUS_USER_ID,
    PAYLOAD:item_id::STRING AS ITEM_ID,
    PAYLOAD:event_type::STRING AS EVENT_TYPE,
    PAYLOAD:position::NUMBER AS POSITION,
    PAYLOAD:model_version::STRING AS MODEL_VERSION,
    PAYLOAD:occurred_at::TIMESTAMP_TZ AS OCCURRED_AT,
    SOURCE_FILENAME,
    SOURCE_ROW_NUMBER,
    LOADED_AT
FROM DEEPSEQUENCE_ANALYTICS.RECOMMENDER.RAW_FEEDBACK
WHERE PAYLOAD:schema_version::NUMBER = 1;

CREATE OR REPLACE VIEW DEEPSEQUENCE_ANALYTICS.RECOMMENDER.MODEL_FEEDBACK_DAILY AS
SELECT
    MODEL_VERSION,
    DATE_TRUNC('DAY', OCCURRED_AT) AS EVENT_DAY,
    COUNT_IF(EVENT_TYPE = 'impression') AS IMPRESSIONS,
    COUNT_IF(EVENT_TYPE = 'click') AS CLICKS,
    COUNT_IF(EVENT_TYPE = 'cart') AS CARTS,
    COUNT_IF(EVENT_TYPE = 'purchase') AS PURCHASES,
    COUNT_IF(EVENT_TYPE = 'dislike') AS DISLIKES,
    DIV0(COUNT_IF(EVENT_TYPE = 'click'), COUNT_IF(EVENT_TYPE = 'impression')) AS CLICK_RATE,
    DIV0(COUNT_IF(EVENT_TYPE = 'purchase'), COUNT_IF(EVENT_TYPE = 'impression')) AS PURCHASE_RATE
FROM DEEPSEQUENCE_ANALYTICS.RECOMMENDER.RECOMMENDATION_FEEDBACK
GROUP BY MODEL_VERSION, EVENT_DAY;
