-- Replace placeholders after the AWS Terraform stack exists.
-- Snowflake storage integrations use a trust handshake; see docs/AWS_SNOWFLAKE_PIPELINE.md.

CREATE STORAGE INTEGRATION IF NOT EXISTS DEEPSEQUENCE_S3_INTEGRATION
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = '<AWS_ROLE_ARN>'
    STORAGE_ALLOWED_LOCATIONS = ('s3://<S3_BUCKET>/feedback/');

CREATE STAGE IF NOT EXISTS DEEPSEQUENCE_ANALYTICS.RECOMMENDER.FEEDBACK_STAGE
    URL = 's3://<S3_BUCKET>/feedback/'
    STORAGE_INTEGRATION = DEEPSEQUENCE_S3_INTEGRATION
    FILE_FORMAT = DEEPSEQUENCE_ANALYTICS.RECOMMENDER.FEEDBACK_JSON;

CREATE PIPE IF NOT EXISTS DEEPSEQUENCE_ANALYTICS.RECOMMENDER.FEEDBACK_PIPE
    AUTO_INGEST = TRUE
AS
COPY INTO DEEPSEQUENCE_ANALYTICS.RECOMMENDER.RAW_FEEDBACK
    (PAYLOAD, SOURCE_FILENAME, SOURCE_ROW_NUMBER)
FROM (
    SELECT $1, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
    FROM @DEEPSEQUENCE_ANALYTICS.RECOMMENDER.FEEDBACK_STAGE
)
ON_ERROR = 'CONTINUE';

-- After creation, run SHOW PIPES LIKE 'FEEDBACK_PIPE' IN SCHEMA
-- DEEPSEQUENCE_ANALYTICS.RECOMMENDER and configure the returned notification_channel
-- on the S3 bucket for object-created events under the feedback/ prefix.
